name: eclint

on: [push, pull_request]

jobs:
    editorconfig_test:

      runs-on: ubuntu-latest
    
      steps:
      - uses: actions/checkout@v1
      - name: Install Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install eclint
        run: npm install -g eclint
      - name: Eclint check
        run: eclint check *
        shell: bash
